Objetivo 3 [IV-22-23]
joseantonio2001/OlivApp pull request #23
Opened 2022-11-17 13:26 UTC by joseantonio2001

2022-11-18 19:47 UTC, joseantonio2001 commented
@JJ solicito revisión 🫡

2022-11-22 10:50 UTC, joseantonio2001 commented
@JJ solicito revisión

2022-11-22 13:30 UTC, JJ requested changes
Lo que has puesto del gestor de dependencias me parece, salvo detalles, correcto. Podías haber hecho lo mismo para el task runner.

2022-11-22 13:30 UTC, JJ commented on docs/gestor-dependencias.md
> +| Hatch                     | pyproject.toml             |       -       | Funciona junto con conda para ayudar a instalar dependencias. Más difícil de entender su funcionamiento |
Hatch tiene también un fichero lock, como es natural.

2022-11-22 13:30 UTC, JJ commented on docs/gestor-dependencias.md
> +| Pipenv                    | Pipfile                    | Pipfile.lock  | Instalaciones lentas                                                                                    |
No usa pyproject.toml, así que es mejor ni considerarlo. Pipfile no es estándar.

2022-11-22 13:30 UTC, JJ commented on docs/task-runner.md
> +Antes de avanzar con el proyecto es necesario elegir un task runner que se adecúe a las caracteísticas del proyecto, que nos permita automatizar tareas agilizando el desarrollo de este.
¿Qué pasa con los criterios en este caso? ¿NO hay criterios? ¿Ni tabla?

2022-11-22 16:44 UTC, joseantonio2001 commented
Cambios hechos! Listo para revisión @JJ

2022-11-22 18:47 UTC, JJ requested changes
Si cambiáis los criterios, quizás tengáis que cambiar las herramientas que las cumplan. No se trata simplemente de poner criterios que sabemos que no habéis seguido porque ya teníais la decisión de antes. En este caso, sucede lo que te he comentado más abajo.

2022-11-22 18:47 UTC, JJ commented on docs/task-runner.md
> +Antes de avanzar con el proyecto es necesario elegir un task runner que se adecúe a las caracteísticas del proyecto, que nos permita automatizar tareas agilizando el desarrollo de este.
Podías haber modificado esta línea para "quitar" el comentario.

2022-11-22 18:47 UTC, JJ commented on docs/task-runner.md
> + - Que resulte una herramientá ágil, fácil de usar y comprender su funcionamiento.
No es un criterio objetivo, pero bueno...

2022-11-22 18:47 UTC, JJ commented on docs/task-runner.md
> +| Gestor de dependencias                  | Descripción                                                                                      | ¿Compatible con petry? | Observaciones
typo: poetry

2022-11-22 18:47 UTC, JJ commented on docs/task-runner.md
> + - Herramienta capaz de trabajar con **poetry** (gestor de dependencias del proyecto) con el fin minimizar el número de ficheros que debemos mantener para el proyecto.
Todos y ninguno son "capaces" de trabajar con poetry. El que se integra mejor, precisamente, no lo pones aquí: poethepoet.

2022-11-23 08:45 UTC, joseantonio2001 commented
> Si cambiáis los criterios, quizás tengáis que cambiar las herramientas que las cumplan. No se trata simplemente de poner criterios que sabemos que no habéis seguido porque ya teníais la decisión de antes. En este caso, sucede lo que te he comentado más abajo.

Okey he reconsiderado el task runner que se adapta mejor a mi proyecto y he estado investigando sobre el task runner que me comentaste poethepoet y considero que es el más correcto para mi proyecto integrandose perfectamente con poetry utilizando el fichero pyproject.toml para definir tareas. En la (documentación)[https://github.com/joseantonio2001/OlivApp/blob/Objetivo-3/docs/task-runner.md] lo especifico mejor.

2022-11-23 08:46 UTC, joseantonio2001 commented
Solicito revisión @JJ

2022-11-23 09:19 UTC, JJ approved these changes
Vamos a darlo por bueno, aunque no has trabajado en muchos de los comentarios hechos. Por favor, hazlo antes del siguiente PR.

2022-11-24 08:40 UTC, merged